I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day+1.rpy", line 5, in script
    call screen day_change(443, "Day 1 - After") with Dissolve(2.0)
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
Exception: Required parameter display_msg has no value.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day+1.rpy", line 5, in script
    call screen day_change(443, "Day 1 - After") with Dissolve(2.0)
  File "renpy/ast.py", line 2010, in execute
    self.call("execute")
  File "renpy/ast.py", line 1998, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "renpy/exports.py", line 3132, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3276, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3694, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/screen.py", line 432, in visit_all
    callback(self)
  File "renpy/display/core.py", line 3694, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/screen.py", line 443, in per_interact
    self.update()
  File "renpy/display/screen.py", line 631, in update
    self.screen.function(**self.scope)
  File "renpy/ast.py", line 159, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "renpy/ast.py", line 123, in apply
    raise Exception("Required parameter %s has no value." % name)
Exception: Required parameter display_msg has no value.

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
And So, I Fall 1.0
Mon Mar 21 18:34:21 2022
